apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
stringData:
  APP_KEY: "base64:n8qVG2TA5YRP1ePl4UlLWo06iLetyt2g6mQ4B5gxP/4="
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "laravel_db"
  DB_USERNAME: "laravel_user"
  DB_PASSWORD: "supersecret"
  DB_SSL_MODE: "DISABLED"   # отключаем SSL


