apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
type: Opaque
stringData:
  APP_KEY: "base64:1L70diHm3rge8t9QZpRyMleFL3RGT4vyAUdVgNyNJ4c="
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "laravel_db"
  DB_USERNAME: "laravel_user"
  DB_PASSWORD: "supersecret"
  DB_SSL_MODE: "DISABLED"   # отключаем SSL


