apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: eduard2005/node-api:7d74c7ffd9ebe896492483e9ab01f94b93b53bde
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  selector:
    app: node-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Inside cluster
      targetPort: 3000  # Container port
      nodePort: 30089   # Port on the node you can access from host
