apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-nginx
  template:
    metadata:
      labels:
        app: laravel-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-nginx-nodeport
spec:
  type: NodePort
  selector:
    app: laravel-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

